In [9]:
import pandas as pd
import numpy as np
import math
from sklearn.linear_model import LinearRegression

In [10]:
data = pd.read_csv('./data/test_scores.csv')

data

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73

In [11]:
X = np.array(data.math)

X

array([92, 56, 88, 70, 80, 49, 65, 35, 66, 67])

In [12]:
y = np.array(data.cs)

y

array([98, 68, 81, 80, 83, 52, 66, 30, 68, 73])

In [13]:
def gradient_descent(X,y):
    m_curr = b_curr = 0
    learning_rate = 0.0002
    n = len(X)
    iterations = 1000000
    cost_prev = 0
    for i in range(iterations):
        y_predicted = m_curr * X + b_curr
        cost = (1/n) * sum([value**2 for value in y - y_predicted])
        md = -(2/n) * sum(X*(y-y_predicted))
        bd = -(2/n) * sum(y-y_predicted)
        m_curr = m_curr - learning_rate * md
        b_curr = b_curr - learning_rate * bd
        if math.isclose(cost, cost_prev, rel_tol = 1e-20):
            break
        cost_prev = cost
        print(f"m: {m_curr}, b: {b_curr}, cost: {cost}, iteration: {i}")
        
    return m_curr, b_curr

In [14]:
m,b = gradient_descent(X,y)

m,b

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



(np.float64(1.0177381667350405), np.float64(1.9150826165722297))

In [16]:
lr = LinearRegression()
lr.fit(data[['math']],data.cs)

LinearRegression()

In [17]:
lr.coef_, lr.intercept_

(array([1.01773624]), np.float64(1.9152193111569034))